name: '.npmrc registry login'

description: 'Logs into NPM registries by managing a .npmrc file'

branding:
  color: 'red'
  icon: 'file-plus'

inputs:
  scope:
    description: 'The registry scope (e.g. @acmeorg)'
    required: true
  registry:
    description: 'The registry domain (e.g. https://npm.pkg.github.com)'
    required: true
  auth-token:
    description: 'The registry auth token'
    required: true
  working-directory:
    description: 'The directory to manage the .npmrc file in (defaults to the currnet directory)'
    required: false

runs:
  using: 'node16'
  main: 'index.js'
